# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c21a046cf66bed001d05bba7bc98147c84f5012d9dea0fb74652265dcd047d5a39e0f07127dc83553b0f970bef3ef0e8499d23b60ddb7ca978a6b540bb970f4a

test:
  secret_key_base: 8ca7666c51200341c08ce6cb50bedd929cf911a824e109d80b9648f473931caca3533f5b6db9863ee5167a3bd1ac39cd1bf0cf758ed6cd718bec18fea3857b2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
